### ISSUE TITLE
Settings issues: Default save, Refresh Recent Logs, & Bug link

### ISSUE THREAD

**Issue by Truncated** [inhumantsar/slurp#22]
v0.1.10
Settings I've had issues with
Changing the target folder for Default Save Location gets reverted.
Steps:

1. Change save location.
2. Close settings
3. Slurp Page - page is made in old location
4. Return to settings, old value is back.

Restarting Obsidian after changing the save location works around this.

---
Refresh button appears to do nothing. It doesn't have any visual response to clicking or message that anything has happened, but logs also do not change. This may be working, but it would be good to show a status message or something to let me know that whatever did (or didn't) occur is expected.

---
Link at bottom for bug submit does nothing. I can hover and it reacts as a link, but no amount of clicking (on the link or the box-arrow icon on the right) changes this.

**Comment by inhumantsar** [comment]
i'm not able to reproduce your save location issue. could you reproduce and post your logs here? uploading the markdown file slurp creates when debug mode is on will make it easier:

1. In settings, turn on debug mode.
2. Close and reopen Obsidian (this is to ensure the logger restarts, future versions won't require this)
3. Slurp a page
4. Open settings, change the save location
5. Slurp another page (same or different, doesn't matter)
6. Open settings, change the save location back and turn off debug mode.
7. Drag the log file from your computer's file manager (`<vault directory>/_slurplogs/slurp-<date>.md`) and drop it onto the comment box for this issue.

I'm going to remove the refresh button altogether. From my testing it *does* work, but it's rare for the textbox to be out of date.

**Comment by inhumantsar** [comment]
apart from the save location issue, these should be resolved in 0.1.11

**Comment by Truncated** [comment]
Save location - I've been trying to recreate it but no dice, so I'll chalk this one up to ghosts in the machine. I isolated your add-on and it works perfectly fine with 0.1.11 and the previous v. so I'm gonna call that one a unique environment issue. :)

I guess removing them is one way to do it. For future consideration, it wasn't whether it worked or not so much as it wasn't clear that it had finished whatever it was supposed to be doing and the UI doesn't give you a good feeling of a positive button push.

What I would recommend is to use the Notice option at the end of whatever command(s) your buttons are doing to let the user know it finished and didn't hit an error.

https://docs.obsidian.md/Reference/TypeScript+API/Notice
