### ISSUE TITLE
onValidate called, no changes detected

### ISSUE THREAD

**Issue by GLISHANG** [inhumantsar/slurp#39]
##### 1716211197085 | DEBUG | onValidate called, no changes detected
- Caller: `HTMLDivElement.<anonymous> (app://obsidian.md/app.js:1:2958823)`

```
{
  "hash": 1309301853
}
```

**Comment by inhumantsar** [comment]
this message is normal and expected. there are many situations where settings validation is requested but isn't necessary. the plugin checks to see if any settings have been modified. if there aren't any changed, this message is logged. if there are changes, then it will update the settings file.

did you notice an issue changing any of your settings?
