### ISSUE TITLE
FR: URI to open a website → Bookmarklet

### ISSUE THREAD

**Issue by chrisgrieser** [inhumantsar/slurp#4]
> IN PROGRESS Browser extension for one-click slurps

I think instead of creating a full-blown extensions, a low-hanging fruit could be to [create a URI](https://docs.obsidian.md/Reference/TypeScript+API/Plugin/registerObsidianProtocolHandler) for this plugin. This could allow users to use their own automation plugins already, but more importantly, it would already allow you to create a simple bookmarklet.

**Comment by inhumantsar** [comment]
I've added an example bookmarklet to the README as part of the v0.1.3 release
