### ISSUE TITLE
Slurp Error

### ISSUE THREAD

**Issue by RookieGordon** [inhumantsar/slurp#41]
url：https://max2d.com/archives/1031
Error：Slurp Error!net::ERR_CERT_DATE_INVALID. If this is a bug, please report it from plugin settings.

**Comment by inhumantsar** [comment]
the website's SSL certificate is expired and slurp can't load pages from sites with bad SSL configurations. it also looks like this site redirects HTTP to HTTPS, so you won't be able to bypass SSL. 

not much that can be done about that unfortunately, except to complain to the website and ask them to renew their certificates.

**Comment by RookieGordon** [comment]
> the website's SSL certificate is expired and slurp can't load pages from sites with bad SSL configurations. it also looks like this site redirects HTTP to HTTPS, so you won't be able to bypass SSL.
> 
> not much that can be done about that unfortunately, except to complain to the website and ask them to renew their certificates.

ok, thanks
