### ISSUE TITLE
Custom folder for slurped notes

### ISSUE THREAD

**Issue by oldjove** [inhumantsar/slurp#9]
Hi, thanks very much for the plugin. Possibly related to #3, but could it be possible to specify the target folder for slurped notes? I'd like to put them in a subfolder of my "sources" folder.

**Comment by inhumantsar** [comment]
[Soon™️!](https://github.com/inhumantsar/slurp/blob/main/main.ts#L240)

**Comment by oldjove** [comment]
Thanks!

**Comment by inhumantsar** [comment]
@oldjove to clarify: are you looking to do this on a per-page basis or in general for all saves?

**Comment by oldjove** [comment]
For all pages. Just to be able to set the default folder is all I'm looking for. 🙂

**Comment by inhumantsar** [comment]
this is available now in v0.1.6!
